### ISSUE TITLE
Language declaration (0.5sp)

### ISSUE THREAD

**Issue by hynek-urban** [windingtree/wiki#50]
Part of #28 is "internationalization". Before a proper internationalization solution arrives, I wonder if we shouldn't at least declare the language of the whole resource in a dedicated field. (Otherwise, it seems hard to use.)

If we decided to do that, the question is where to put the declaration (in other words, what's "the resource"). Is it the whole hotel (i.e. it's data index)? Or is it a single off-chain document (e.g. description)?

**Comment by JirkaChadima** [comment]
Well, if we do this, I'd put it on the top level of the whole thing as a hotel's property.

It might be also interesting to add something like `spokenLanguages` field to the hotel.

**Comment by JirkaChadima** [comment]
I'll use this as a tracking issue:

In order to add support for this throughout the platform, we further need to:

* [ ]  show support for this in wt-fixtures
* [ ]  bump swagger docs in wt-read-api + test support for this
* [ ]  bump swagger docs in wt-write-api + test support for this
* [ ]  show these fields in the hotel explorer

Non critical

* [ ]  bump swagger docs in wt-search-api + test support for this
* [ ]  add support for search by default locale in wt-search-api

**Comment by JirkaChadima** [comment]
Everything should be ready everywhere, closing for now.
