### ISSUE TITLE
Thoughts on architecture-draft-v0.1.md

### ISSUE THREAD

**Issue by dannyvaughton** [windingtree/wiki#7]
Just curious, why is reputation out of the scope for the first iteration? It's probably the most important element of the whole system. Will this be baked into WT or are you relying on OTAs to implement reputation? Or both?

Also, just an event based system for availability will never be 100% due to internet outages etc. Companies like Airbnb regularly sweep APIs over & over again to ensure availability is always correct. There's nothing worse than double bookings (from instant books) and telling the guest they can't come :)

**Comment by JirkaChadima** [comment]
Hi, thanks for your input. We have to tackle things one by one and the reputation system really does not make any sense when we don't have the hotel data and the ability to make bookings. That's why this order. Also the document does not necessarily mean that we won't release all those things together at once in the future. It's just that our focus is for now elsewhere. As per who will do the reputation system - we definitely need some system of our own, but maybe we won't implement it by ourselves and instead re-use some existing solution. That's to be decided when we are dealing with the reputation system.

We're very well aware that there are many culprits in availability and we have to deal with them. We're thinking about multiple solutions and I'm pretty sure we will make something public once we decide on how to solve it. We obviously don't want double bookings to happen :)

Maybe @kvbik or @AugustoL have something to add?

**Comment by AugustoL** [comment]
@dannyvaughton Nice to have you here discussing with us the first iteration.

Like @JirkaChadima saidit is not out of the first iteration, but actually there is no way we can implement it without the bookings happening on the system first. WT will have a reputation system.

Regarding double bookings we dont want to happen, We havent thought in the booking process yet, but I imagine that we will require a signature from the hotel owner at first for the booking to happen, this signature will have a lifespan of X min. before that it can be  used and the booking cant happen, smth like that.

**Comment by JirkaChadima** [comment]
@dannyvaughton Do you have any more thoughts on this? We've just started to finalize this in #10, so if you have any more remarks, please drop them there. I am closing this for now.
