### ISSUE TITLE
Address format (1sp)

### ISSUE THREAD

**Issue by mikozza** [windingtree/wiki#84]
I propose to change the address structure to Google standard:

House Number, Street Direction, Street Name, Street Suffix, City, State, Zip, Country

https://support.google.com/mapcontentpartners/answer/160409?hl=en

Or other more structured formats. 

https://github.com/OpenCageData/address-formatting

But definitely, the street and house number should be separated.

Also, I think for a country should be used standardized enum which should be mentioned in API and hosted on some URL.

https://en.wikipedia.org/wiki/List_of_ISO_3166_country_codes

https://github.com/windingtree/wiki/blob/ebf034be7464ebb1244ed77e97b08996d986da40/hotel-data-swagger.yaml#L500

**Comment by JirkaChadima** [comment]
Thank you for the proposal, in the first iteration we aimed for user-friendlyness ~ i. e. easy manual input and we didn't even bothered with any validation whatsoever. So this will definitely be an improvement!

I am leaning slightly more to the OpenCage format which is Google-independent (always good to be independent). I'll have to take a look into if it's not too region-specific, but it looks very good.

The country codes are actualy ISO 3166-1 alpha-2 codes and it is mentioned in the docs. It might have not been rendered somewhere though.

**Comment by JirkaChadima** [comment]
Well, geodata is always fun. Thanks a ton for pointing me to the OpenCage's address-formatting library, I fell in love with their initiative and when I have some time I will write a JS implementation of that - because it's so useful!

As their repository works as a funnel for multiple geocoders with using multiple aliases, I have decided to use their top-level naming which I believe comes from the naming used in [Nominatim from OSM](https://github.com/openstreetmap/Nominatim/blob/6c1977b448e8b195bf96b6144674ffe0527e79de/lib/lib.php#L63). So picking up from [this list](https://github.com/OpenCageData/address-formatting/blob/master/conf/components.yaml), the address in WT platform shall look like (datatypes might not be strings in all cases)

```
{
  "address": {
    "house_number": "",
    "house": "",
    "road": "",
    "neighbourhood": "",
    "city": "",
    "county": "",
    "postcode": "",
    "state_district": "",
    "state": "",
    "country": "",
    "country_code": "",
    "village": "",
    "region": "",
    "island": "",
    "continent": ""
  }
}
```

This will bring use these benefits:

- Possibility to fill WT addresses from OSM search (via [Nominatim](https://nominatim.openstreetmap.org/), [Photon](https://photon.komoot.de/api/?q=chomut)) or even [OpenCage](https://opencagedata.com) itself
- Ease of use of widely used client-side formatting with an already sort-of standardized behaviour (there is a PHP implementation and I will write a JS one)

I'm not sure if we will be able to come up with a minimal required set of fields, but I will put up the formatting rules to some analysis and we shall see. After that I'll do a PR against the data standard and I will write down the following steps.

**Comment by mikozza** [comment]
Great ! Looks really good :-)

**Comment by JirkaChadima** [comment]
JS implementation for displaying addresses: https://www.npmjs.com/package/@fragaria/address-formatter

**Comment by JirkaChadima** [comment]
I will use this as a tracking issue.

In order to add support for this throughout the platform, we further need to:

* [ ] change the postal address references in Legal entity and contacts
* [ ] change data in wt-fixtures
* [ ] bump swagger docs in wt-read-api + test support for this
* [ ] bump swagger docs in wt-write-api + test support for this
* [ ] reupload all of the data with new address format
* [ ] change the way addresses are formatted in hotel-explorer
* [ ] change the way addresses are used in wt-booking-api

Non critical

* [ ]    bump swagger docs in wt-search-api + test support for this

This might also be leaking somewhere else which I can't see right now.

**Comment by JirkaChadima** [comment]
This will land in the next release. Closing.
