### ISSUE TITLE
Room type category (0.5sp)

### ISSUE THREAD

**Issue by mikozza** [windingtree/wiki#86]
I propose to add category field like and define enum list of room type categories like room, apartment, vila, bunk ..which would be used in the data and make this list available on hosted URL as part of the documentation,

https://github.com/windingtree/wiki/blob/ebf034be7464ebb1244ed77e97b08996d986da40/hotel-data-swagger.yaml#L148

**Comment by JirkaChadima** [comment]
This is very similar to #85, the biggest hurdle is to put together the enum. Do you have any tips for a starting point?

**Comment by mikozza** [comment]
We will prepare something and post it here.

**Comment by Honza65** [comment]
Here are the room categories.

Bungalow
Cabin
Studio
Tree House
Villa
Yurt
Teepee
Tent
Room
Apartment
Bunk
Shared Room
Barn
Boat
Bungalow
Cabin
Castle
Chalet
Cottage
Lodge
Recreation vehicle
Studio
Tree House
Villa
Yurt
Teepee

**Comment by JirkaChadima** [comment]
@czervenka Was this omitted from https://github.com/orgs/windingtree/projects/3 intentionally? I don't think it's that big and we could squeeze it in

**Comment by czervenka** [comment]
@JirkaChadima I overlooked that probably. Fixed.

**Comment by JirkaChadima** [comment]
I've extended the list slightly with the help of OTA and Expedia enumerations. I will use this as a tracking issue.

In order to add support for this throughout the platform, we further need to:

* [ ]    show support for this in wt-fixtures
* [ ]    bump swagger docs in wt-read-api + test support for this
* [ ]    bump swagger docs in wt-write-api + test support for this
* [ ]    show the field in the hotel explorer

Non critical

* [ ]    bump swagger docs in wt-search-api + test support for this
* [ ]    add support for search by room type category in wt-search-api

**Comment by JirkaChadima** [comment]
Everything should be ready. I'm not sure how the search by room type category should work in the search-api, so I've dropped it from this functionality.
