### ISSUE TITLE
Rate plans modifiers - absolute number (0.5sp)

### ISSUE THREAD

**Issue by JirkaChadima** [windingtree/wiki#89]
Percentage adjustment of the modifiers (different price for two guests) might be a pain (I had to calculate the modifier adjustment for every price). Extending modifiers in a way that they are able to handle fixed modified price would make this actually a lot easier.

**Comment by czervenka** [comment]
Do I understand that correctly that:

- [list of modifiers](https://github.com/windingtree/wiki/blob/ac3c003c0bf05cda1a33f6b704cb3a48f2e2d1c4/hotel-data-swagger.yaml#L293) is bound to [rate plan](https://github.com/windingtree/wiki/blob/ac3c003c0bf05cda1a33f6b704cb3a48f2e2d1c4/hotel-data-swagger.yaml#L215) so that one modifier can be used to one price only
- only one modifier can be used at a time for one person (selected base on [price algorithm](https://github.com/windingtree/wiki/blob/ac3c003c0bf05cda1a33f6b704cb3a48f2e2d1c4/hotel-data-swagger.yaml#L219))

So we can achieve the same results by percentage as well as absolute numbers in modifiers?

**Comment by JirkaChadima** [comment]
We can, but it's much clearer to write

```
amount: -100
```

instead of

```
amount: -43.123
```

Also it scales a little better, because you don't have to recompute the amount every time you change the base price.

**Comment by czervenka** [comment]
Great, I see. Thanks.

**Comment by czervenka** [comment]
For record, the idea is to keep both possibilities: absolute modifier as well as percentage.

**Comment by czervenka** [comment]
After short discussion with @martinbilek: It's a small change, let's implement it since it helps us soon and it will not yet brake anything.

**Comment by JirkaChadima** [comment]
I will use this as a tracking issue.

In order to add support for this throughout the platform, we further need to:

* [ ]  reflect the changes in wt-pricing-algorithms
* [ ]  bump swagger docs in wt-read-api + test support for this
* [ ]  bump swagger docs in wt-write-api + test support for this

Non critical

* [ ] change data in wt-fixtures

This might also be leaking somewhere else which I can't see right now.

**Comment by JirkaChadima** [comment]
This is implemented in the [data model](https://github.com/windingtree/wiki/tree/868b5d2685b1cd70647020978141be820ddccd30) and reflected in [wt-pricing-algorithms](https://github.com/windingtree/wt-pricing-algorithms/releases/tag/v0.5.0).

Closing
